name = "wushi-edgetunnel1212"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true
workers_dev = false

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "54a9cb2a3f294a21b7b3ef705ec93830"				#KV数据库id
